baseURL = 'http://sparcie.neocities.org/'
languageCode = 'en-us'
title = 'SPARCies site'
theme = 'terminal'
sectionPagesMenu = 'main'
mainSections = ["About"]
#theme = "hugo-blog-awesome"
# [markup]
#   [markup.highlight]
#     anchorLineNos = false
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ''
#     hl_inline = false
#     lineAnchors = ''
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     noHl = false
#     style = 'monokai'
#     tabWidth = 4